INSERT INTO EMPLOYEE (EMPLOYEE_ID,ADDRESS,CITY,COUNTRY_NAME,DEPARTMENT,EMAIL_EMPLOYEE,EMPLOYEE_AGE,FIRST_NAME,LAST_NAME,PHONE_NUMBER,SALARY,STATE) VALUES('24300','2306 Palisade Ave','New York','USA','DEVELOPMENT_DEPARTMENT','CarolSchaaf@gmail.com','30','Carol','Schaaf','+1-541-754-3010',6000,'NJ')
INSERT INTO EMPLOYEE (EMPLOYEE_ID,ADDRESS,CITY,COUNTRY_NAME,DEPARTMENT,EMAIL_EMPLOYEE,EMPLOYEE_AGE,FIRST_NAME,LAST_NAME,PHONE_NUMBER,SALARY,STATE) VALUES('24301','240 Fifth Ave.','New York','USA','DEVELOPMENT_DEPARTMENT','SusanShipe@gmail.com','30','Susan','Shipe','+1-541-754-3010',6000,'NY')

