INSERT INTO EMPLOYEE (DEPARTMENT,EMAIL_EMPLOYEE,FIRST_NAME,LAST_NAME,PHONE_NUMBER,SALARY) values ('ENGINEERING','DMURPHY@CLASSICMODELCARS.COM','MURPHY','DIANE','92964245',10000.0)
INSERT INTO EMPLOYEE (DEPARTMENT,EMAIL_EMPLOYEE,FIRST_NAME,LAST_NAME,PHONE_NUMBER,SALARY) values ('ENGINEERING','MPATTERSO@CLASSICMODELCARS.COM','PATTERSON','MARY','92964245',10000.0)
INSERT INTO EMPLOYEE (DEPARTMENT,EMAIL_EMPLOYEE,FIRST_NAME,LAST_NAME,PHONE_NUMBER,SALARY) values ('ENGINEERING','JFIRRELLI@CLASSICMODELCARS.COM','FIRRELLI','JEFF','92964245',10000.0)
INSERT INTO EMPLOYEE (DEPARTMENT,EMAIL_EMPLOYEE,FIRST_NAME,LAST_NAME,PHONE_NUMBER,SALARY) values ('ENGINEERING','WPATTERSON@CLASSICMODELCARS.COM','PATTERSON','WILLIAM','92964245',10000.0)
INSERT INTO EMPLOYEE (DEPARTMENT,EMAIL_EMPLOYEE,FIRST_NAME,LAST_NAME,PHONE_NUMBER,SALARY) values ('ENGINEERING','WPATTERSON@CLASSICMODELCARS.COM','BONDUR','GERARD','92964245',10000.0)





